// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Asset struct {
	ID   *string `json:"Id"`
	Name *string `json:"Name"`
}

type Case struct {
	ID                 *string  `json:"Id"`
	Name               *string  `json:"Name"`
	Asset              *Asset   `json:"Asset"`
	CaseNumber         *string  `json:"CaseNumber"`
	Origin             *string  `json:"Origin"`
	Owner              *User    `json:"Owner"`
	Reason             *string  `json:"Reason"`
	IsClosed           *string  `json:"IsClosed"`
	IsClosedOnCreate   *string  `json:"IsClosedOnCreate"`
	Contact            *Contact `json:"Contact"`
	CreatedBy          *User    `json:"CreatedBy"`
	ClosedDate         *string  `json:"ClosedDate"`
	CreatedDate        *string  `json:"CreatedDate"`
	IsDeleted          *string  `json:"IsDeleted"`
	Description        *string  `json:"Description"`
	IsEscalated        *string  `json:"IsEscalated"`
	LastModifiedBy     *User    `json:"LastModifiedBy"`
	LastModifiedDate   *string  `json:"LastModifiedDate"`
	LastReferencedDate *string  `json:"LastReferencedDate"`
	LastViewedDate     *string  `json:"LastViewedDate"`
}

type Contact struct {
	ID   *string `json:"Id"`
	Name *string `json:"Name"`
}

type InputAsset struct {
	Name *string `json:"Name"`
}

type InputCase struct {
	AssetID         *string `json:"AssetId"`
	BusinessHoursID *string `json:"BusinessHoursId"`
	CaseNumber      *string `json:"CaseNumber"`
	Origin          *string `json:"Origin"`
	OwnerID         *string `json:"OwnerId"`
	Reason          *string `json:"Reason"`
	IsClosed        *string `json:"IsClosed"`
	Name            *string `json:"Name"`
	IsDeleted       *string `json:"IsDeleted"`
	Description     *string `json:"Description"`
	IsEscalated     *string `json:"IsEscalated"`
}

type InputContact struct {
	Name *string `json:"Name"`
}

type InputUser struct {
	Name *string `json:"Name"`
}

type User struct {
	ID   *string `json:"Id"`
	Name *string `json:"Name"`
}
