// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package models

type Account struct {
	Id   *string `json:"Id"`
	Name *string `json:"Name"`
}

type InputAccount struct {
	Name *string `json:"Name"`
}
